// users.ts
export interface User {
  _id: string;
  first_name: string;
  last_name: string;
  email: string;
  phone_number: number;
  address: string;
  user_role: string;
  department: string;
  position: string;
  status?: string;
  gender?: string;
  profile_img?: string;
  completedTasks: string[];
  feedbacks: string[];
  coordinates?: any[];
  startedJobAt?: string;
  kpiRating?: number;
  __v: number;
  refresh_token?: string;
}

export const mockUsers: User[] = [
  {
    _id: "68b53b60ab6fb9253b70b607",
    first_name: "Gansukh",
    last_name: "Sodgerel",
    email: "sodgerel.g@techpack.mn",
    phone_number: 88111152,
    address: "Ulaanbaatar1",
    user_role: "worker",
    department: "Backend Developer",
    position: "Engineering",
    status: "inactive",
    gender: "male",
    profile_img:
      "https://res.cloudinary.com/dsvivujtj/image/upload/v1757192322/avatarMaleLvl2_tv7ba0.png",
    completedTasks: ["68b55e8336c215ba667892f0", "68c134dc195852f1184ce19e"],
    feedbacks: ["68baf7a4d3f563c2708da475", "68bc2cf9341284693cdc9739"],
    coordinates: [],
    startedJobAt: "2025-08-31T16:00:00.000Z",
    __v: 113,
  },
  {
    _id: "68be906cc1d9bff1d522d269",
    first_name: "Temuujin",
    last_name: "Munkhtulga",
    email: "temuujin.m@techpack.mn",
    phone_number: 99109910,
    address: "Ulaanbaatar",
    user_role: "worker",
    department: "Backend Developer",
    position: "Engineering",
    status: "remote",
    kpiRating: 4.9,
    completedTasks: [],
    feedbacks: [],
    __v: 0,
  },
  {
    _id: "68bfaecaf329ddcee748734e",
    first_name: "User",
    last_name: "Userlast",
    email: "user@techpack.mn",
    phone_number: 99882233,
    address: "UB",
    user_role: "hr",
    department: "Techpack",
    position: "HR",
    gender: "male",
    completedTasks: [],
    feedbacks: [],
    __v: 0,
  },
  {
    _id: "68c1352f195852f1184ce1a9",
    first_name: "Temuujin",
    last_name: "Test",
    email: "temuujin.test@techpack.mn",
    phone_number: 99887766,
    address: "Ulaanbaatar",
    user_role: "worker",
    department: "Backend Developer",
    position: "Engineering",
    status: "active",
    gender: "other",
    completedTasks: [],
    feedbacks: [],
    coordinates: [],
    __v: 0,
  },
  {
    _id: "68c140aa195852f1184ce1b1",
    first_name: "Anujin",
    last_name: "Bat",
    email: "anujin.bat@techpack.mn",
    phone_number: 99551122,
    address: "Darkhan",
    user_role: "worker",
    department: "Frontend Developer",
    position: "Engineering",
    status: "active",
    gender: "female",
    completedTasks: ["task-1", "task-2"],
    feedbacks: ["feedback-1"],
    __v: 0,
  },
  {
    _id: "68c141aa195852f1184ce1b2",
    first_name: "Batbayar",
    last_name: "Bold",
    email: "batbayar.bold@techpack.mn",
    phone_number: 99001234,
    address: "Erdenet",
    user_role: "worker",
    department: "QA",
    position: "Tester",
    status: "inactive",
    gender: "male",
    completedTasks: [],
    feedbacks: [],
    __v: 0,
  },
  {
    _id: "68c142aa195852f1184ce1b3",
    first_name: "Delger",
    last_name: "Tuvshin",
    email: "delger.t@techpack.mn",
    phone_number: 93112233,
    address: "Ulaanbaatar",
    user_role: "worker",
    department: "UI/UX",
    position: "Designer",
    status: "remote",
    gender: "male",
    completedTasks: ["task-3"],
    feedbacks: ["feedback-2"],
    __v: 0,
  },
  {
    _id: "68c143aa195852f1184ce1b4",
    first_name: "Sarnai",
    last_name: "Enkh",
    email: "sarnai.e@techpack.mn",
    phone_number: 94445566,
    address: "Ulaanbaatar",
    user_role: "worker",
    department: "Marketing",
    position: "Specialist",
    status: "active",
    gender: "female",
    completedTasks: [],
    feedbacks: [],
    __v: 0,
  },
  {
    _id: "68c144aa195852f1184ce1b5",
    first_name: "Tuvshin",
    last_name: "Ganbaatar",
    email: "tuvshin.g@techpack.mn",
    phone_number: 99889977,
    address: "UB",
    user_role: "worker",
    department: "Backend Developer",
    position: "Engineering",
    status: "active",
    gender: "male",
    completedTasks: ["task-4"],
    feedbacks: ["feedback-3"],
    __v: 0,
  },
  {
    _id: "68c145aa195852f1184ce1b6",
    first_name: "Enkhtuya",
    last_name: "Purev",
    email: "enkhtuya.p@techpack.mn",
    phone_number: 88776655,
    address: "UB",
    user_role: "hr",
    department: "HR",
    position: "Manager",
    status: "active",
    gender: "female",
    completedTasks: [],
    feedbacks: ["feedback-4"],
    __v: 0,
  },
];
